# Generated by Django 4.2.6 on 2023-10-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(max_length=165),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.FloatField(),
        ),
    ]
