# Generated by Django 4.2.6 on 2023-10-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_meal_is_published_alter_meal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='slug',
            field=models.SlugField(default='SOME STRING', unique=True),
        ),
    ]
