# Generated by Django 4.2.6 on 2023-11-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
